// Generated by scripts/generate_protocol.py from FastAPI OpenAPI schemas.
// Do not edit this file directly.

export interface CameraInfo {
  id: string;
  name: string;
  device: string;
}

export interface CameraLatencyRequest {
  latency_ms: number;
}

export interface ControllerEvent {
  timestamp: number;
  level: "info" | "warning" | "error";
  message: string;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface RobotRequest {
  robot_ip: string;
}

export interface RuntimeCapabilities {
  leader_transport: "local" | "remote_explicit" | "remote_browser_pairing";
  simulation_available: boolean;
  physical_available: boolean;
  camera_streaming: boolean;
  structured_logging: boolean;
  video_transport: "mjpeg";
  max_robots: 1;
}

export interface StartRequest {
  mode: "dry_run" | "simulation" | "physical";
  confirmation?: string | null;
}

export interface TeleopSnapshot {
  protocol_version: number;
  session_id: string;
  capabilities: RuntimeCapabilities;
  timestamp: number;
  state: TeleopState;
  mode: "dry_run" | "simulation" | "physical" | null;
  leader_connected: boolean;
  robot_connected: boolean;
  robot_ip: string;
  torque_enabled_ids: Array<number>;
  leader_degrees: Array<number> | null;
  target_degrees: Array<number> | null;
  gripper_command: number | null;
  robot_status: XArmStatus | null;
  loop_rate_hz: number;
  command_latency_ms: number | null;
  last_sample_age_ms: number | null;
  fault: string | null;
  events: Array<ControllerEvent>;
}

export type TeleopState = "idle" | "leader_ready" | "ready" | "starting" | "running" | "stopping" | "stopped" | "fault";

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export interface XArmStatus {
  connected: boolean;
  version: string;
  mode: number;
  state: number;
  error_code: number;
  warning_code: number;
  joint_degrees: Array<number>;
  gripper_position: number;
  gripper_force: number | null;
  gripper_status: number | null;
  gripper_error_code: number;
}
