#!/usr/bin/env python3
"""Generate TypeScript API types from FastAPI's OpenAPI component schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "frontend" / "src" / "types.ts"


def _literal(value: object) -> str:
    """Render a JSON-compatible value as a TypeScript literal."""
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    return json.dumps(value, ensure_ascii=False)


def _typescript_type(schema: dict[str, Any]) -> str:
    """Translate the OpenAPI schema subset emitted by this project."""
    reference = schema.get("$ref")
    if isinstance(reference, str):
        return reference.rsplit("/", 1)[-1]
    if "const" in schema:
        return _literal(schema["const"])
    enum = schema.get("enum")
    if isinstance(enum, list):
        return " | ".join(_literal(value) for value in enum)
    alternatives = schema.get("anyOf") or schema.get("oneOf")
    if isinstance(alternatives, list):
        translated = dict.fromkeys(_typescript_type(value) for value in alternatives)
        return " | ".join(translated)

    schema_type = schema.get("type")
    if schema_type in ("integer", "number"):
        return "number"
    if schema_type == "string":
        return "string"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"Array<{_typescript_type(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", ()))
        if isinstance(properties, dict) and properties:
            fields = []
            for name, value in properties.items():
                optional = "" if name in required else "?"
                fields.append(f"{json.dumps(name)}{optional}: {_typescript_type(value)};")
            return "{ " + " ".join(fields) + " }"
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_typescript_type(additional)}>"
        return "Record<string, unknown>"
    return "unknown"


def _component(name: str, schema: dict[str, Any]) -> str:
    """Render one named OpenAPI component as a TypeScript declaration."""
    properties = schema.get("properties")
    if schema.get("type") == "object" and isinstance(properties, dict):
        required = set(schema.get("required", ()))
        lines = [f"export interface {name} {{"]
        for field_name, field_schema in properties.items():
            optional = "" if field_name in required else "?"
            lines.append(f"  {field_name}{optional}: {_typescript_type(field_schema)};")
        lines.append("}")
        return "\n".join(lines)
    return f"export type {name} = {_typescript_type(schema)};"


def generate() -> str:
    """Return deterministic TypeScript declarations from the live FastAPI schema."""
    from uarm_xarm6_teleop.web.app import app

    schemas = app.openapi().get("components", {}).get("schemas", {})
    declarations = [_component(name, schemas[name]) for name in sorted(schemas)]
    header = (
        "// Generated by scripts/generate_protocol.py from FastAPI OpenAPI schemas.\n"
        "// Do not edit this file directly.\n\n"
    )
    return header + "\n\n".join(declarations) + "\n"


def main() -> None:
    """Write generated types or fail if the committed output is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when frontend/src/types.ts is stale",
    )
    args = parser.parse_args()
    generated = generate()
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != generated:
            raise SystemExit(
                "frontend/src/types.ts is stale; run `python scripts/generate_protocol.py`"
            )
        return
    OUTPUT_PATH.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
